# Generated by Django 4.2.24 on 2025-09-25 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Bodega Principal Cúcuta', max_length=150)),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('vendedor', 'Vendedor'), ('operario_bodega', 'Operario de Bodega'), ('verificador', 'Verificador'), ('admin', 'Administrador')], max_length=50)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='colaborador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('transito', 'Tránsito'), ('alistamiento', 'Alistamiento'), ('por_verificar', 'Por Verificar'), ('rechazado_x_verificar', 'Rechazado x Verificar'), ('verificado', 'Verificado'), ('empacado_x_despachar', 'Empacado x Despachar'), ('despachado_x_facturar', 'Despachado x Facturar'), ('despachado', 'Despachado'), ('entregado', 'Entregado'), ('devuelto', 'Devuelto'), ('anulado', 'Anulado')], default='transito', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('colaborador_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estante', models.CharField(max_length=50)),
                ('fila', models.CharField(max_length=50)),
                ('columna', models.CharField(max_length=50)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='wms.bodega')),
            ],
            options={
                'unique_together': {('bodega', 'estante', 'fila', 'columna')},
            },
        ),
        migrations.CreateModel(
            name='TransaccionBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_transaccion', models.DateTimeField()),
                ('banco_origen', models.CharField(max_length=100)),
                ('url_comprobante', models.URLField(blank=True, null=True)),
                ('validada', models.BooleanField(default=False)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='wms.pedido')),
                ('validada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Identificador único del producto', max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='wms.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wms.producto')),
            ],
            options={
                'unique_together': {('pedido', 'producto')},
            },
        ),
    ]
